#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# ///
"""Evidence batches: every public silo page per open candidate, for the Claude stage (issue #54, Plan 09 L2).

    uv run tools/silo-candidates/batch.py plan      # print what would be written, write nothing
    uv run tools/silo-candidates/batch.py apply     # write .local/silo-batches/<product>/

One folder per product that has a silo product:
  README.md    the open web-backed candidates (after the triage ledger), each with its dictionary
               definition and every public page carrying the tag: URL, title, probability,
               retrieval date and the `silo: path@sha` pin to cite; then the product's current
               matrix rows (ID and status)
  pages/*.md   each cited page's body at the silo ref, frontmatter removed

The folder is gitignored and rebuilt on every run. Only public pages are included: repository
documents and source files are left out entirely, not just unnamed. Read-only for the silo
(git objects at a pinned ref); the only files written are under .local/silo-batches/.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
from pathlib import Path, PurePosixPath

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent

sys.path.insert(0, str(HERE))
import candidates  # noqa: E402
from review import FM_RE, ID_HEADERS, ReadOnlyViolation, capability_rows, cat_batch, cell_ids, frontmatter, split_cells  # noqa: E402

OUT_DIR = ".local/silo-batches"


def definitions(text: str) -> dict[str, tuple[str, str]]:
    """Dictionary ID -> (name, description), from every `Sub-feature ID | Name | Description` table."""
    out, header = {}, None
    for line in text.splitlines():
        cells = split_cells(line) if line.startswith("|") else []
        if not cells:
            header = None
        elif cells[0].startswith(ID_HEADERS):
            header = cells
        elif header and not set(cells[0]) <= set("-: ") and len(cells) >= 3:
            row = dict(zip(header, cells))
            for i in cell_ids(cells[0]):
                out.setdefault(i, (row.get("Name", ""), row.get("Description", "")))
    return out


def page_file(path: str) -> str:
    return hashlib.sha256(path.encode("utf-8")).hexdigest()[:16] + ".md"


def _md(text: str) -> str:
    return " ".join(str(text).split()).replace("\\|", "|").replace("|", "\\|")


def build(ccfg: dict, silo: Path, ref: str) -> tuple[str, dict[str, dict[str, str]]]:
    """(silo sha, {product: {relative file: content}})."""
    repo = ccfg["repo"]
    signals: dict[str, list[candidates.Signal]] = {}
    candidates.build(ccfg, silo, ref, open_signals=signals)   # checks the ledger too
    sha = candidates.git(silo, "rev-parse", "--verify", f"{ref}^{{commit}}").strip()
    mapping = candidates.load_mapping(repo / ccfg["reconciliation_tsv"])
    aka: dict[str, set[str]] = {}
    for i, tag in mapping.items():
        aka.setdefault(tag, set()).add(i)
    defs = definitions((repo / "feature-dictionary.md").read_text(encoding="utf-8"))
    data = ccfg["silo_data_dir"]
    paths = sorted({w[3] for sigs in signals.values() for s in sigs for w in s.web})
    blobs = cat_batch(silo, [f"{sha}:{data}/{p}" for p in paths])
    folders = {d.name: d for d in (repo / ccfg["products_dir"]).glob("*/*") if d.is_dir()}

    out: dict[str, dict[str, str]] = {}
    for slug in sorted(signals):
        files: dict[str, str] = {}
        sigs = signals[slug]
        L = [f"# Evidence batch — {slug}", "",
             f"Generated by `tools/silo-candidates/batch.py` from `prod_info_silo` commit `{sha[:10]}`. "
             "Local working file: never commit it, never edit it; re-run the tool.", "",
             "**Leads, not facts.** A silo tag is never evidence. Evidence is a page's text, quoted word for word and "
             "cited by its URL plus the pin below. Record one ledger row per candidate "
             "(`tools/silo-candidates/triage.tsv`, `web_docs` = the Web count here). Rules: Plan 09.", "",
             f"{len(sigs)} open web-backed candidates.", ""]
        for s in sigs:
            ids = sorted({s.tag} | aka.get(s.tag, set()))
            L += [f"## `{s.tag}`", "",
                  f"- Web pages: {len(s.web)} · Shared with another silo product: {s.shared} of {s.total} entries",
                  "- Also known as: " + (", ".join(f"`{i}`" for i in ids if i != s.tag) or "—")]
            for i in ids:
                if i in defs:
                    L.append(f"- Dictionary `{i}`: {_md(defs[i][0])} — {_md(defs[i][1])}")
            if not any(i in defs for i in ids):
                L.append("- Dictionary: no entry for this tag or its aliases")
            L += ["", "| # | Page | Probability | Retrieved | Cite as | Body |", "|---|---|---|---|---|---|"]
            for n, (prob, title, url, path) in enumerate(s.web, 1):
                body = blobs.get(f"{sha}:{data}/{path}", "")
                fm = frontmatter(body)
                pf = page_file(path)
                files[f"pages/{pf}"] = FM_RE.sub("", body, count=1).strip() + "\n"
                L.append(f"| {n} | [{_md(title) or url}]({url}) | {prob:.2f} | {fm.get('updated_at', '—')[:10]} | "
                         f"`{url}` (silo: `{data}/{path}@{sha[:8]}`) | [pages/{pf}](pages/{pf}) |")
            L.append("")
        L += ["## Current matrix rows", ""]
        d = folders.get(slug)
        for m in sorted(d.glob("features/*/feature-matrix.md")) if d else []:
            rows = list(capability_rows(m.read_text(encoding="utf-8")))
            if not rows:
                continue
            L += [f"### `{m.relative_to(repo).as_posix()}`", "", "| ID | Status |", "|---|---|"]
            for _, _, cells in rows:
                first = next(iter(cells.values()), "")
                L.append(f"| {', '.join(cell_ids(first)) or _md(first)[:40]} | "
                         f"{_md(cells.get('Current support', cells.get('Status', '')))[:80]} |")
            L.append("")
        files["README.md"] = "\n".join(L)
        out[slug] = files
    return sha, out


def write(root: Path, batches: dict[str, dict[str, str]]) -> None:
    """Rebuild the batch folder. Refuses any path that is not under it."""
    root = root.resolve()
    if root.parent.name != ".local" or root.name != "silo-batches":
        raise ReadOnlyViolation(f"{root} is not .local/silo-batches")
    if root.exists():
        shutil.rmtree(root)
    for slug, files in batches.items():
        for rel, text in files.items():
            p = (root / slug / rel).resolve()
            if root not in p.parents:
                raise ReadOnlyViolation(f"{p} is outside {root}")
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text, encoding="utf-8")


def run(ccfg: dict, command: str, silo: Path | None = None, ref: str | None = None) -> str:
    sha, batches = build(ccfg, silo or ccfg["silo_path"], ref or ccfg["silo_ref"])
    n_cands = sum(f["README.md"].count("\n## `") for f in batches.values())
    n_pages = sum(sum(k.startswith("pages/") for k in f) for f in batches.values())
    summary = f"{len(batches)} batches, {n_cands} candidates, {n_pages} pages at silo {sha[:10]}"
    if command == "plan":
        return "would write " + summary
    write(ccfg["repo"] / OUT_DIR, batches)
    return f"wrote {OUT_DIR}: {summary}"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("command", choices=["plan", "apply"])
    ap.add_argument("--silo", type=Path, help="override silo_path from the candidates config")
    ap.add_argument("--ref", help="override silo_ref from the candidates config")
    a = ap.parse_args(argv)
    try:
        print(run(candidates.load_config(), a.command, a.silo.resolve() if a.silo else None, a.ref))
    except (candidates.CandidatesError, ReadOnlyViolation) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    except Exception as e:  # noqa: BLE001 — exit 2 for every error; no message, it could quote silo content
        print(f"error: unexpected {type(e).__name__}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
