#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# ///
"""Evidence-gap report: where the silo cannot check this repository's sources (issue #37).

    uv run tools/evidence-gaps/gaps.py plan      # print the report, write nothing
    uv run tools/evidence-gaps/gaps.py apply     # write reports/evidence-gaps.md

Three lists: matrices that cite no URL (invisible to the staleness check), products whose
silo coverage is thin against their matrices, and cited domains the silo does not track,
split by what could be done about them. Proposing silo seed URLs is out of scope here: that
is prod_info_silo#47, which takes this report as input.

Read-only by construction (reuses tools/silo-review: git-object reads at a pinned ref, one
guarded write). A gap is a prompt for a human, never evidence for a ✅ or ❌.
"""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from collections import defaultdict
from pathlib import Path, PurePosixPath

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent

sys.path.insert(0, str(HERE.parent / "silo-review"))
import review  # noqa: E402
from review import (NOT_CHECKABLE, DROPPED, ReadOnlyViolation, domain, guarded_write, host_matches,  # noqa: E402
                    host_of, repo_path_key)

GROUPS = [
    ("crawlable", "Crawlable and compliant — candidate silo seeds (prod_info_silo#47)"),
    ("excluded", "Excluded by policy — terms of service or not a product source"),
    ("internal", "Internal systems — not crawlable by design"),
    ("not-a-page", "Other GitHub pages — organisation pages, trees, links without a file"),
]

# GitHub URLs that are not file permalinks, by the path part after owner/repo. Release, wiki
# and repository pages are product sources (issue #37: "GitHub releases" are crawlable);
# issue trackers are excluded, like youtrack.jetbrains.com.
GITHUB_CRAWLABLE = {"", "releases", "tags", "wiki"}
GITHUB_EXCLUDED = {"issues", "pull", "pulls", "discussions"}
# First path segments that are GitHub pages, not owners (github.com/orgs/x is not a repository).
GITHUB_RESERVED = {"orgs", "topics", "sponsors", "marketplace", "features", "collections", "settings", "search"}


def group_of(norm: str, cfg: dict) -> str:
    if host_matches(norm, cfg["internal_domains"]):
        return "internal"
    if host_matches(norm, cfg["excluded_domains"]):
        return "excluded"
    if host_of(norm) == "github.com" and not repo_path_key(norm):
        parts = norm.split("?", 1)[0].split("/")[1:]
        if len(parts) >= 2 and parts[0].lower() not in GITHUB_RESERVED:
            kind = parts[2] if len(parts) > 2 else ""
            if kind in GITHUB_CRAWLABLE:
                return "crawlable"
            if kind in GITHUB_EXCLUDED:
                return "excluded"
        return "not-a-page"
    return "crawlable"


def _plural(n: int, word: str) -> str:
    return f"{n} {word}" if n == 1 else f"{n} {word}s"


def build(cfg: dict, silo_root: Path, ref: str) -> str:
    repo = cfg["repo"]
    rcfg = review.load_config(repo / cfg["review_config"], repo)
    silo = review.Silo.load(silo_root, ref, rcfg.get("silo_data_dir", "data"))
    matrices, cites, dates = review.parse_repo(rcfg, repo)
    silo.load_dropped(set(cites))
    cache: dict = {}

    # 1. matrices with no URL
    no_url = sorted(m.file for m in matrices if not m.citations)
    by_product: dict[str, list[str]] = defaultdict(list)
    for f in no_url:
        by_product["/".join(PurePosixPath(f).parts[1:3])].append(f)

    # 2. thin silo coverage
    snapshot = json.loads((repo / cfg["snapshot"]).read_text(encoding="utf-8"))
    rows = {r["analysis_folder"]: r for r in snapshot.get("products", []) if r.get("analysis_folder")}
    thin = []
    for folder in sorted({"/".join(PurePosixPath(m.file).parts[:3]) for m in matrices}):
        ids = set()
        for m in matrices:
            if m.file.startswith(folder + "/"):
                ids |= review.matrix_table_ids((repo / m.file).read_text(encoding="utf-8"))[0]
        r = rows.get(folder)
        docs = (r["web_pages"] + r["repo_docs"]) if r else 0
        if not r or docs < len(ids):
            thin.append((folder, len(ids), docs, "no silo product" if not r else ""))

    # 3. cited URLs the silo does not track
    gaps: dict[str, dict[str, set[str]]] = {g: defaultdict(set) for g, _ in GROUPS}
    for norm, cl in cites.items():
        rds = [dates[c.file] for c in cl if dates.get(c.file)]
        v = review.classify(norm, min(rds) if rds else None, silo, cache)
        if v.status in (NOT_CHECKABLE, DROPPED):
            gaps[group_of(norm, cfg)][domain(norm)].add(norm)
    total = sum(len(u) for g in gaps.values() for u in g.values())
    snap_sha = str(snapshot.get("silo", {}).get("commit", ""))

    L = [
        "# Evidence gaps",
        "",
        f"> Generated by [`tools/evidence-gaps`](../tools/evidence-gaps/README.md) from `prod_info_silo` commit "
        f"`{silo.sha[:10]}` ({silo.commit_date}) and silo snapshot `{snap_sha[:10]}`. "
        "Do not edit by hand; re-run the tool.",
        "",
    ]
    if snap_sha != silo.sha:
        L += [f"> **Warning:** the snapshot (section 2) is from silo `{snap_sha[:10]}`, not `{silo.sha[:10]}` "
              "(sections 1 and 3). Regenerate it with `tools/silo-snapshot` for one consistent view.", ""]
    L += [
        "Where the silo cannot check this repository's sources. A gap is a prompt for a human, never evidence for a ✅ or ❌.",
        "",
        "## 1. Matrices that cite no URL",
        "",
        f"{len(no_url)} of {len(matrices)} feature matrices cite no URL, so the staleness check cannot cover them "
        "(their sources are research files or source-code audits).",
        "",
    ]
    if no_url:
        L += ["| Product | Matrices |", "|---|---|"]
        for prod, files in sorted(by_product.items()):
            L.append(f"| `{prod}` | " + " · ".join(f"[{PurePosixPath(f).parts[-2]}](../{f})" for f in files) + " |")
        L.append("")
    L += ["## 2. Thin silo coverage", "",
          "Products whose silo holds fewer documents (web pages + repo docs) than their matrices have IDs.", ""]
    if thin:
        L += ["| Product | Matrix IDs | Silo documents | Note |", "|---|---|---|---|"]
        L += [f"| `{f}` | {n} | {d} | {note or '—'} |" for f, n, d, note in thin]
    else:
        L.append("None.")
    L += ["", "## 3. Cited URLs the silo does not track", "",
          f"{total} of {len(cites)} distinct cited URLs are *not checkable* or *dropped by silo* in the "
          "[review queue](review-queue.md), grouped by what could be done.", ""]
    for g, title in GROUPS:
        doms = gaps[g]
        n = sum(len(u) for u in doms.values())
        L += [f"### {title}", "", f"{_plural(n, 'URL')} on {_plural(len(doms), 'domain')}.", ""]
        if doms:
            L += ["| Domain | URLs |", "|---|---|"]
            L += [f"| {d} | {len(u)} |" for d, u in sorted(doms.items(), key=lambda kv: (-len(kv[1]), kv[0]))]
            L.append("")
    L.append("Domain groups are set in [`evidence-gaps.toml`](../tools/evidence-gaps/evidence-gaps.toml).")
    L.append("")
    return "\n".join(L)


def load_config(path: Path = HERE / "evidence-gaps.toml", repo: Path = REPO) -> dict:
    cfg = tomllib.loads(path.read_text(encoding="utf-8"))
    cfg["repo"] = repo
    cfg["silo_path"] = (repo / cfg["silo_path"]).resolve()
    cfg["output_path"] = (repo / cfg["output"]).resolve()
    if cfg["output_path"].parent != (repo / "reports").resolve() or not cfg["output_path"].name.startswith("evidence-gaps") \
            or cfg["output_path"].suffix != ".md":
        raise ReadOnlyViolation(f"{cfg['output_path']} is not reports/evidence-gaps*.md (other reports belong to other tools)")
    return cfg


def run(cfg: dict, command: str, silo_root: Path | None = None, ref: str | None = None) -> str:
    report = build(cfg, silo_root or cfg["silo_path"], ref or cfg["silo_ref"])
    if command == "plan":
        return report
    guarded_write(cfg["output_path"], report, cfg["output_path"])
    return f"wrote {cfg['output']}"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("command", choices=["plan", "apply"])
    ap.add_argument("--silo", type=Path, help="override silo_path from the config")
    ap.add_argument("--ref", help="override silo_ref from the config")
    a = ap.parse_args(argv)
    print(run(load_config(), a.command, a.silo.resolve() if a.silo else None, a.ref))
    return 0


if __name__ == "__main__":
    sys.exit(main())
